### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [sxeony/CPP202309-P#1]
1. 이미지 입출력에 대한 기능은 수업 중 배울 예정에 없기 때문에, 개인 역량으로  해결하시거나, 특정 상황을 가정 (옷 색상, 종류, 재질, 사이즈 등을 출럭)하는 것이 필요해보입니다.
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by sxeony** [comment]
넵 감사합니당 !
